# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-10 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grundgeruest', '0003_auto_20180304_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='farbschema',
            field=models.CharField(choices=[('https://olymp.piokg.de/static/Grundgeruest/css/w3-theme-amber.css', 'Zeus'), ('https://olymp.piokg.de/static/Grundgeruest/css/w3-theme-blue.css', 'Poseidon'), ('https://olymp.piokg.de/static/Grundgeruest/css/w3-theme-brown.css', 'Demeter'), ('https://olymp.piokg.de/static/Grundgeruest/css/w3-theme-indigo.css', 'indigo'), ('https://olymp.piokg.de/static/Grundgeruest/css/w3-theme-cyan.css', 'türkis'), ('https://olymp.piokg.de/static/Grundgeruest/css/w3-theme-light-green.css', 'Artemis'), ('https://olymp.piokg.de/static/Grundgeruest/css/w3-theme-orange.css', 'Hephaistos'), ('https://olymp.piokg.de/static/Grundgeruest/css/w3-theme-yellow.css', 'Apollo')], default='braun', max_length=255),
        ),
    ]
