# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-26 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grundgeruest', '0004_profil_farbschema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='farbschema',
            field=models.CharField(choices=[('https://olymp.piokg.de/static/Grundgeruest/css/w3-theme-amber.css', 'Zeus'), ('https://olymp.piokg.de/static/Grundgeruest/css/w3-theme-blue.css', 'Poseidon'), ('https://olymp.piokg.de/static/Grundgeruest/css/w3-theme-indigo.css', 'Hera'), ('https://olymp.piokg.de/static/Grundgeruest/css/w3-theme-brown.css', 'Demeter'), ('https://olymp.piokg.de/static/Grundgeruest/css/w3-theme-yellow.css', 'Apollo'), ('https://olymp.piokg.de/static/Grundgeruest/css/w3-theme-light-green.css', 'Artemis'), ('https://olymp.piokg.de/static/Grundgeruest/css/w3-theme-dark-grey.css', 'Athene'), ('https://olymp.piokg.de/static/Grundgeruest/css/w3-theme-red.css', 'Ares'), ('https://olymp.piokg.de/static/Grundgeruest/css/w3-theme-pink.css', 'Aphrodite'), ('https://olymp.piokg.de/static/Grundgeruest/css/w3-theme-grey.css', 'Hermes'), ('https://olymp.piokg.de/static/Grundgeruest/css/w3-theme-orange.css', 'Hephaistos'), ('https://olymp.piokg.de/static/Grundgeruest/css/w3-theme-cyan.css', 'Dionysus')], default='https://olymp.piokg.de/static/Grundgeruest/css/w3-theme-dark-grey.css', max_length=255),
        ),
    ]
