# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-06 23:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_markdown.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kommentar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeit_erstellt', models.DateTimeField(auto_now_add=True)),
                ('zeit_geaendert', models.DateTimeField(auto_now=True)),
                ('nutzer_geaendert', models.TextField(default='0', editable=False)),
                ('text', django_markdown.models.MarkdownField()),
            ],
            options={
                'ordering': ['-zeit_geaendert'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Liste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeit_erstellt', models.DateTimeField(auto_now_add=True)),
                ('zeit_geaendert', models.DateTimeField(auto_now=True)),
                ('nutzer_geaendert', models.TextField(default='0', editable=False)),
            ],
            options={
                'ordering': ['-zeit_geaendert'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='kommentar',
            name='liste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kommentare', to='Kommentare.Liste'),
        ),
    ]
