<<<<<<< 33b6413fb751fd7d5e667d8477b4de8c81623851
# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-02 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
# Generated by Django 2.1 on 2018-11-29 17:36

from django.db import migrations, models
import django_extensions.db.fields
import martor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kommentar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('text', martor.models.MartorField()),
            ],
            options={
                'verbose_name_plural': 'Kommentare',
                'verbose_name': 'Kommentar',
            },
        ),
        migrations.CreateModel(
            name='Liste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'verbose_name_plural': 'Kommentarlisten',
                'verbose_name': 'Kommentarliste',
            },
        ),
    ]
