# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-20 21:41
from __future__ import unicode_literals

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('Kommentare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kommentar',
            name='text',
            field=martor.models.MartorField(),
        ),
    ]
