# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-11 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Grundgeruest', '0003_auto_20180304_0037'),
        ('Kommentare', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kommentar',
            options={'verbose_name': 'Kommentar', 'verbose_name_plural': 'Kommentare'},
        ),
        migrations.AlterModelOptions(
            name='liste',
            options={'verbose_name': 'Kommentarliste', 'verbose_name_plural': 'Kommentarlisten'},
        ),
        migrations.AddField(
            model_name='kommentar',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kommentare', to='Grundgeruest.Profil'),
        ),
    ]
