# Generated by Django 2.1.4 on 2018-12-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nutzer', '0002_auto_20181204_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutzerprofil',
            name='nachname',
            field=models.CharField(blank=True, max_length=99),
        ),
        migrations.AlterField(
            model_name='nutzerprofil',
            name='plz',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='nutzerprofil',
            name='stadt',
            field=models.CharField(blank=True, max_length=99),
        ),
        migrations.AlterField(
            model_name='nutzerprofil',
            name='strasse',
            field=models.CharField(blank=True, max_length=99),
        ),
        migrations.AlterField(
            model_name='nutzerprofil',
            name='vorname',
            field=models.CharField(blank=True, max_length=99),
        ),
    ]
