# Generated by Django 2.1.11 on 2019-09-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nutzer', '0004_remove_nutzerprofil_anrede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutzerprofil',
            name='vorname',
            field=models.CharField(max_length=99),
        ),
    ]
